### ISSUE TITLE
NullPointerException generating solution summary and solution shapefiles

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#170]
experiment id: CPLEX_on_10_26_2021,_12:58:23_PM_34b575ee-5790-4298-84fa-64220b5034c4

From Ryan:

> One thing to mention is I tried doing “1, 2, 3” for the Capture Target, which I don’t know if we have that capability in Community Case Studies yet.

**Comment by machristie** [comment]
server side stack trace 

```
[2021-11-05 19:22:34,199 simccs_maptool.simccs_helper:266 ERROR] Error occurred when calling loadSolution: ['java.lang.NullPointerException', 'dataStore.DataInOut.loadSolution(DataInOut.java:786)', 'dataStore.DataStorer.loadSolution(DataStorer.java:618)']
Traceback (most recent call last):
  File "/Users/machrist/Airavata/django/maptool/simccs_maptool/simccs_helper.py", line 262, in load_solution
    solution = data.loadSolution(results_dir)
  File "jnius/jnius_export_class.pxi", line 857, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 937, in jnius.JavaMethod.call_method
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: java.lang.NullPointerException
```

The NullPointerException occurs on this line: https://github.com/simccs/SimCCS/blob/public/src/dataStore/DataInOut.java#L786. My guess is that the `unidirEdge` is null.

**Comment by machristie** [comment]
I think the problem may be that the mps file was generated with the case study's own candidate network. But then when loading the solution the code regenerates a candidate network for just those sources and sinks and then the indices of edges, etc. in the candidate network are off.

I'm going to try to replicate this situation:
- I'll setup Ryan's scenario again, select the same sources and sinks but won't generate a candidate network so that the case study's candidate network is used to generate the mps
- I'll also try generating the candidate network for those sources and sinks and compare the generated mps file
- I can also write some code to try to load Ryan's solution using the case study's candidate network

**Comment by machristie** [comment]
I've run into a separate issue, generating the candidate network is failing to save the candidate network files into the experiment data directory:

```
Failed to generate geojson result files
Traceback (most recent call last):
  File "/var/www/portals/django-simccs/venv/src/simccs-maptool/simccs_maptool/views.py", line 232, in experiment_result
    request, experiment, simccs_helper.get_shapefiles_dir(scenario_dir))
  File "/var/www/portals/django-simccs/venv/src/simccs-maptool/simccs_maptool/views.py", line 398, in _copy_directory_to_experiment
    request, dir_name, experiment_id=experiment_id)
  File "/var/www/portals/django-simccs/venv/lib64/python3.6/site-packages/airavata_django_portal_sdk/user_storage/api.py", line 715, in create_user_dir
    storage_resource_id, resource_path = backend.create_dirs(final_path, dir_names=dir_names, create_unique=create_unique)
  File "/var/www/portals/django-simccs/venv/lib64/python3.6/site-packages/airavata_django_portal_sdk/user_storage/backends/django_filesystem_provider.py", line 117, in create_dirs
    raise Exception(f"Directory {final_path} already exists")
Exception: Directory /var/www/portals/gateway-user-data/django-simccs/machrist@iu.edu/Southeast_US_2012/CPLEX_on_1182021_40633_PM/shapeFiles already exists
```

But, the shapeFiles do get created, so creating an mps file with the sources and sinks unique candidate network does work since the same candidate network is used when creating the shapefiles.

**Comment by machristie** [comment]
TODO

- [ ] add 'Candidate-Network' input file (optional, i.e, not required) to Cplex application interface on beta
- [ ] update mps generation code to return the candidate network input file data product uri
- [ ] use the candidate network when generating the experiment scenario directory
- [ ] add 'Candidate-Network' input file to Cplex application interface on production

**Comment by machristie** [comment]
Tests

- :white_check_mark:  generate shapefiles with candidate network
- :white_check_mark:  generate shapefiles without candidate network
- :white_check_mark: generate candidate network for community case study experiment
  - https://beta.simccs.scigap.org/workspace/experiments/CPLEX_on_11_9_2021%2C_10%3A31%3A06_AM_0b1582fa-706f-4609-a078-43ef166ea730/
- :white_check_mark:  don't generate candidate network, use community case study's cand. network for the experiment
  - https://beta.simccs.scigap.org/workspace/experiments/CPLEX_on_11_9_2021%2C_10%3A32%3A50_AM_c01fe34d-ac6e-405f-bfe3-832a3f2ac316/

And I'm going some other testing on the beta site now that I've pushed the fix there.

**Comment by machristie** [comment]
Added saving the candidate network to the national cost surface experiments too.

**Comment by machristie** [comment]
This is deployed https://simccs.org
