### ISSUE TITLE
candidate network error: JVM exception occurred: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#188]
User reported error. User reports that it affects the Ordos Basin 2014 case study.

**Comment by machristie** [comment]
error log

```
[Wed Feb 23 23:08:05.495496 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692] Error occurred when calling makeCandidateNetworkShapeFiles: ['java.lang.ArrayIndexOutOfBoundsException']
[Wed Feb 23 23:08:05.495522 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692] Traceback (most recent call last):
[Wed Feb 23 23:08:05.495525 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692]   File "/var/www/portals/django-iu-geology-survey/venv/src/simccs-maptool/simccs_maptool/simccs_helper.py", line 141, in make_candidate_network_shapefiles
[Wed Feb 23 23:08:05.495527 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692]     data.makeCandidateShapeFiles(results_dir)
[Wed Feb 23 23:08:05.495529 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692]   File "jnius/jnius_export_class.pxi", line 769, in jnius.JavaMethod.__call__
[Wed Feb 23 23:08:05.495532 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692]   File "jnius/jnius_export_class.pxi", line 863, in jnius.JavaMethod.call_method
[Wed Feb 23 23:08:05.495534 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692]   File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
[Wed Feb 23 23:08:05.495537 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692] jnius.JavaException: JVM exception occurred: java.lang.ArrayIndexOutOfBoundsException
[Wed Feb 23 23:08:05.495541 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62692] 
[Wed Feb 23 23:08:07.910514 2022] [wsgi:error] [pid 15559] [remote 68.45.27.210:62694] [2022-02-23 23:08:07,910 django_airavata.apps.api.views:1766 ERROR] Frontend error: JVM exception occurred: java.lang.ArrayIndexOutOfBoundsException: "{\\"url\\": \\"/maptool/candidate-network/\\", \\"body\\": {}, \\"status\\": 500, \\"response\\": {\\"detail\\": \\"JVM exception occurred: java.lang.ArrayIndexOutOfBoundsException\\"}}"\\nstacktrace: \\n    AiravataAPI</processFetch/</< (https://simccs.org/static/django_airavata_api/dist/airavata-api.js:1:79377)
```

**Comment by machristie** [comment]
Generating the Candidate Network works on beta.simccs.scigap.org. I checked the datasets and they need to be synced. Specifically looks like the CostNetwork files are missing for Ordos Basin.

**Comment by machristie** [comment]
Syncing the data has fixed the issue. Just to document, what I did was:

```
ssh pga@scigap11.sciencegateways.iu.edu
```
then
```
cd /data/gateway-user-data/simccs-datasets/
./copy_from_dev.sh
```

Where copy_from_dev.sh contains the following:
```sh
#!/bin/sh

rsync -azP pga@pgadev.scigap.org:/data/gateway-user-data/simccs-datasets/ .
```
