### ISSUE TITLE
NullPointerException generating candidate-network

### ISSUE THREAD

**Issue by machristie** [SciGaP/simccs-maptool#208]
Server side error:

```
Error occurred when calling makeCandidateNetworkShapeFiles: [
    'java.lang.NullPointerException',
    'dataStore.DataStorer.generateCandidateGraph(DataStorer.java:111)',
    'dataStore.DataStorer.getGraphEdgeRoutes(DataStorer.java:214)',
    'dataStore.DataInOut.makeCandidateShapeFiles(DataInOut.java:1020)',
    'dataStore.DataStorer.makeCandidateShapeFiles(DataStorer.java:606)']
Traceback (most recent call last):
  File "/var/www/portals/django-iu-geology-survey/venv/src/simccs-maptool/simccs_maptool/simccs_helper.py", line 141, in make_candidate_network_shapefiles
    data.makeCandidateShapeFiles(results_dir)
  File "jnius/jnius_export_class.pxi", line 769, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 863, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: java.lang.NullPointerException



```

The error is occuring at this line: https://github.com/simccs/SimCCS/blob/public/src/dataStore/DataStorer.java#L111

It seems there are "outliers" in the data. Sources or sinks that belong to cells that are not part of the cost map.

**Comment by machristie** [comment]
Sources and sinks that are generating the issue:

[Sinks.txt](https://github.com/SciGaP/simccs-maptool/files/11083400/Sinks.txt)
[Sources.txt](https://github.com/SciGaP/simccs-maptool/files/11083403/Sources.txt)
